title: Daniel Quesada Camacho
email: danqueca@gmail.com
description: >- 
  Senior .NET Engineer | Team Lead | Full Stack Developer
baseurl: "" 
url: "https://danqueca.github.io/"
theme: minima
github_username: danqueca
